import type { Finding, RepositoryEvidence, Rule, RuleMetadata } from "./index.js";

const meta = (id: string, area: RuleMetadata["area"], name: string, purpose: string, recommendation: string): RuleMetadata => ({ id, version: 1, area, name, purpose, severity: "medium", weight: 1, recommendation, falsePositiveConsiderations: ["Evidence can be documented outside conventional filenames."] });
const files = (repository?: RepositoryEvidence): Readonly<Record<string, string>> => repository?.files ?? {};
const sourceFor = (repository: RepositoryEvidence | undefined, names: readonly string[]): string | undefined => names.find((name) => Boolean(files(repository)[name]));
const matchingSource = (repository: RepositoryEvidence | undefined, pattern: RegExp): string | undefined => Object.entries(files(repository)).find(([, value]) => pattern.test(value))?.[0];
const hasPath = (repository: RepositoryEvidence | undefined, pattern: RegExp): string | undefined => Object.keys(files(repository)).find((path) => pattern.test(path.replaceAll("\\", "/")));

const setup001: Rule = { metadata: meta("CR-SETUP-001", "setup", "Setup prerequisites are discoverable", "A contributor can find a contributor-facing setup guide.", "Document versions and prerequisites in the README or contributing guide."), evaluate: (context) => { const source = sourceFor(context.repository, ["README.md", "CONTRIBUTING.md"]); return { rule: setup001.metadata, outcome: source ? "pass" : "fail", message: source ? "A contributor-facing guide exists." : "No README or CONTRIBUTING guide was found.", evidence: source ? [{ kind: "file", source }] : [], recommendation: setup001.metadata.recommendation }; } };
const setup002: Rule = { metadata: meta("CR-SETUP-002", "setup", "Runtime prerequisites are stated", "A contributor can identify the required runtime or toolchain version.", "Document the runtime/toolchain name and supported version in contributor-facing documentation."), evaluate: (context) => { const source = matchingSource(context.repository, /\b(?:node(?:\.js)?|python|java|go|rust|ruby)\s*(?:v?\d+(?:\.\d+){0,2}|version|versions)\b|\b(?:runtime|toolchain|prerequisite|required version)\b/i); const guide = sourceFor(context.repository, ["README.md", "CONTRIBUTING.md"]); return { rule: setup002.metadata, outcome: source ? "pass" : guide ? "unknown" : "not-applicable", message: source ? "Runtime or prerequisite terminology is documented." : guide ? "A guide exists, but no runtime prerequisite was identified." : "No contributor guide was available for runtime analysis.", evidence: source ? [{ kind: "text", source }] : [], recommendation: setup002.metadata.recommendation }; } };
const setup003: Rule = { metadata: meta("CR-SETUP-003", "setup", "Package-manager installation is discoverable", "A contributor can identify how dependencies are installed.", "Document the dependency installation command and keep it aligned with the committed manifest/lockfile."), evaluate: (context) => { const installSource = matchingSource(context.repository, /\b(?:npm|pnpm|yarn|bun)\s+(?:install|i|ci)|\bpip\s+install|\b(?:poetry|uv|pdm)\s+install|\bcargo\s+(?:build|test)|\bgo\s+(?:mod\s+download|build)|\b(?:mvn|gradle|sbt)\s+(?:test|build)|\b(?:deno|docker)\s+(?:task|build|compose)\b/i); const manifest = hasPath(context.repository, /(^|\/)(?:package\.json|pyproject\.toml|requirements(?:-dev)?\.txt|cargo\.toml|go\.mod|pom\.xml|build\.gradle(?:\.kts)?|build\.sbt|composer\.json|gemfile|mix\.exs|deno\.jsonc?|bunfig\.toml|flake\.nix|dockerfile)$/i); return { rule: setup003.metadata, outcome: installSource ? "pass" : manifest ? "fail" : "unknown", message: installSource ? "A dependency installation or build command is documented." : manifest ? "A project manifest exists, but no installation command was identified." : "No supported project manifest was found for package-manager analysis.", evidence: installSource ? [{ kind: "text", source: installSource }] : manifest ? [{ kind: "file", source: manifest }] : [], recommendation: setup003.metadata.recommendation }; } };
const setup004: Rule = { metadata: meta("CR-SETUP-004", "setup", "Development setup steps are actionable", "A new contributor can follow a path from checkout to local development.", "Add ordered checkout, dependency, configuration, and local-development steps to README or CONTRIBUTING.md."), evaluate: (context) => { const source = matchingSource(context.repository, /\b(?:clone|getting started|set\s*up|setup|install dependencies|run locally|development environment|developing)\b/i); const guide = sourceFor(context.repository, ["README.md", "CONTRIBUTING.md"]); return { rule: setup004.metadata, outcome: source ? "pass" : guide ? "fail" : "unknown", message: source ? "Development setup language is present." : guide ? "A contributor guide exists, but actionable setup language was not found." : "No contributor guide was available for development setup analysis.", evidence: source ? [{ kind: "text", source }] : [], recommendation: setup004.metadata.recommendation }; } };
const setup005: Rule = { metadata: meta("CR-SETUP-005", "setup", "Environment configuration is discoverable", "A contributor can identify required environment configuration without guessing secrets.", "Document required environment variables and provide safe example values or an example environment file."), evaluate: (context) => { const envFile = hasPath(context.repository, /(^|\/)(?:\.env\.example|\.env\.sample|example\.env)$/i); const source = matchingSource(context.repository, /\b(?:environment variable|configuration|process\.env|os\.environ|export\s+[A-Z_][A-Z0-9_]*)\b/i); return { rule: setup005.metadata, outcome: envFile || source ? "pass" : "not-applicable", message: envFile ? "An example environment file is present." : source ? "Environment configuration guidance is present." : "No environment configuration requirement was identified.", evidence: envFile ? [{ kind: "file", source: envFile }] : source ? [{ kind: "text", source }] : [], recommendation: setup005.metadata.recommendation }; } };

const test001: Rule = { metadata: meta("CR-TEST-001", "testing", "Test command is discoverable", "A contributor can identify how to run tests.", "Document a test command and expected result."), evaluate: (context) => { const source = matchingSource(context.repository, /\b(?:npm|pnpm|yarn)\s+(?:test|run\s+test)|\b(?:pytest|cargo\s+test|go\s+test|mvn\s+test|gradle\s+test)\b|\b(?:run|execute|invoke)\s+(?:the\s+)?tests?\b/i); return { rule: test001.metadata, outcome: source ? "pass" : "unknown", message: source ? "A test command or explicit test instruction is present." : "No test command was found in inspected evidence.", evidence: source ? [{ kind: "text", source }] : [], recommendation: test001.metadata.recommendation }; } };
const test002: Rule = { metadata: meta("CR-TEST-002", "testing", "Reproduction guidance is present", "A contributor can reproduce a reported behavior or validate a change.", "Document reproduction steps, a minimal example/fixture, expected behavior, and observed behavior where relevant."), evaluate: (context) => { const source = matchingSource(context.repository, /\b(?:reproduc(?:e|ible|tion)|steps to reproduce|minimal example|fixture|expected behavior|actual behavior|test case)\b/i); const guide = sourceFor(context.repository, ["README.md", "CONTRIBUTING.md"]); return { rule: test002.metadata, outcome: source ? "pass" : guide ? "unknown" : "not-applicable", message: source ? "Reproduction or validation guidance is present." : guide ? "A guide exists, but reproduction guidance was not identified." : "No contributor guide was available for reproduction analysis.", evidence: source ? [{ kind: "text", source }] : [], recommendation: test002.metadata.recommendation }; } };
const test003: Rule = { metadata: meta("CR-TEST-003", "testing", "Continuous integration is discoverable", "A contributor can identify automated validation and its entry point.", "Document the CI checks and link to the workflow or explain how to run the same checks locally."), evaluate: (context) => { const workflow = hasPath(context.repository, /(^|\/)\.github\/workflows\/[^/]+\.(?:yml|yaml)$/i); const text = matchingSource(context.repository, /\b(?:continuous integration|github actions|CI checks?|automated checks?)\b/i); return { rule: test003.metadata, outcome: workflow || text ? "pass" : "unknown", message: workflow ? "A GitHub Actions workflow was found." : text ? "Continuous-integration guidance is present." : "No CI workflow or CI guidance was found.", evidence: workflow ? [{ kind: "file", source: workflow }] : text ? [{ kind: "text", source: text }] : [], recommendation: test003.metadata.recommendation }; } };
const test004: Rule = { metadata: meta("CR-TEST-004", "testing", "Test expectations are stated", "A contributor can tell what a successful test or reproduction should demonstrate.", "Document expected results, relevant test environment, test data, or fixture requirements."), evaluate: (context) => { const source = matchingSource(context.repository, /\b(?:expected result|should pass|test environment|test data|fixture|assert(?:ion)?|verification criteria)\b/i); const testCommand = matchingSource(context.repository, /\b(?:npm|pnpm|yarn)\s+(?:test|run\s+test)|\b(?:pytest|cargo\s+test|go\s+test|mvn\s+test|gradle\s+test)\b/i); return { rule: test004.metadata, outcome: source ? "pass" : testCommand ? "unknown" : "not-applicable", message: source ? "Test expectations or test-environment guidance is present." : testCommand ? "A test command exists, but expected results were not identified." : "No test command was available for test-expectation analysis.", evidence: source ? [{ kind: "text", source }] : [], recommendation: test004.metadata.recommendation }; } };

const contrib001: Rule = { metadata: meta("CR-CONTRIB-001", "contribution", "Contribution workflow exists", "A contributor can find contribution guidance.", "Add CONTRIBUTING.md with branch, change, test, and review steps."), evaluate: (context) => { const source = sourceFor(context.repository, ["CONTRIBUTING.md"]); return { rule: contrib001.metadata, outcome: source ? "pass" : "fail", message: source ? "CONTRIBUTING.md exists." : "CONTRIBUTING.md is missing.", evidence: source ? [{ kind: "file", source }] : [], recommendation: contrib001.metadata.recommendation }; } };
const contrib002: Rule = { metadata: meta("CR-CONTRIB-002", "contribution", "Pull-request workflow is discoverable", "A contributor can prepare and submit a change using the project workflow.", "Document branch, commit, pull-request, and required-check steps in CONTRIBUTING.md."), evaluate: (context) => { const source = matchingSource(context.repository, /\b(?:pull requests?|PRs?|branch(?:es)?|commit message|open a PR|submit a change)\b/i); const guide = sourceFor(context.repository, ["CONTRIBUTING.md"]); return { rule: contrib002.metadata, outcome: source ? "pass" : guide ? "fail" : "unknown", message: source ? "Pull-request or change-submission guidance is present." : guide ? "CONTRIBUTING.md exists, but pull-request workflow guidance was not identified." : "No CONTRIBUTING.md was available for pull-request workflow analysis.", evidence: source ? [{ kind: "text", source }] : [], recommendation: contrib002.metadata.recommendation }; } };
const contrib003: Rule = { metadata: meta("CR-CONTRIB-003", "contribution", "Review expectations are discoverable", "A contributor can understand how changes are reviewed and accepted.", "Document review criteria, required approvals/checks, and maintainer expectations."), evaluate: (context) => { const source = matchingSource(context.repository, /\b(?:code review|review(?:ed|er|s)?|maintainer approval|approval required|required checks|code owners|maintainers?)\b/i); const guide = sourceFor(context.repository, ["CONTRIBUTING.md"]); return { rule: contrib003.metadata, outcome: source ? "pass" : guide ? "fail" : "unknown", message: source ? "Review or maintainer expectations are present." : guide ? "CONTRIBUTING.md exists, but review expectations were not identified." : "No CONTRIBUTING.md was available for review-expectation analysis.", evidence: source ? [{ kind: "text", source }] : [], recommendation: contrib003.metadata.recommendation }; } };
const contrib004: Rule = { metadata: meta("CR-CONTRIB-004", "contribution", "Support and contact path exists", "A contributor can ask questions or find the appropriate community/support channel.", "Add SUPPORT.md or document a safe support, discussion, or maintainer-contact path."), evaluate: (context) => { const file = sourceFor(context.repository, ["SUPPORT.md"]); const source = matchingSource(context.repository, /\b(?:support|ask questions?|community discussion|discussion forum|contact (?:the )?maintainers?|help channel)\b/i); const guide = sourceFor(context.repository, ["README.md", "CONTRIBUTING.md"]); return { rule: contrib004.metadata, outcome: file || source ? "pass" : guide ? "unknown" : "not-applicable", message: file ? "SUPPORT.md exists." : source ? "A support or contact path is documented." : guide ? "A project guide exists, but no support/contact path was identified." : "No contributor-facing support path was available for analysis.", evidence: file ? [{ kind: "file", source: file }] : source ? [{ kind: "text", source }] : [], recommendation: contrib004.metadata.recommendation }; } };
const security001: Rule = { metadata: meta("CR-SECURITY-001", "security", "Security reporting path exists", "A contributor can report a vulnerability safely.", "Add SECURITY.md with a private reporting path and supported versions."), evaluate: (context) => { const source = sourceFor(context.repository, ["SECURITY.md"]); return { rule: security001.metadata, outcome: source ? "pass" : "fail", message: source ? "SECURITY.md exists." : "SECURITY.md is missing.", evidence: source ? [{ kind: "file", source }] : [], recommendation: security001.metadata.recommendation }; } };

const issueText = (context: Parameters<Rule["evaluate"]>[0]): string | undefined => context.issue ? `${context.issue.title}\n${context.issue.body}` : undefined;
const issueContains = (text: string | undefined, terms: readonly string[]): boolean => Boolean(text && terms.some((term) => text.toLowerCase().includes(term.toLowerCase())));
const issueFinding = (rule: Rule, context: Parameters<Rule["evaluate"]>[0], matched: boolean, message: string): Finding => ({ rule: rule.metadata, outcome: context.issue ? matched ? "pass" : "fail" : "not-applicable", message, evidence: context.issue && matched ? [{ kind: "issue-text", source: context.issue.source }] : [], recommendation: rule.metadata.recommendation });
const issue001: Rule = { metadata: meta("CR-ISSUE-001", "issue", "Issue states a concrete problem or goal", "A contributor can understand what needs to change and why.", "State the problem, user impact, or concrete goal in the title and body."), evaluate: (context) => { const text = issueText(context); return issueFinding(issue001, context, Boolean(text && text.trim().length >= 20 && issueContains(text, ["bug", "problem", "goal", "feature", "request", "failure", "fails", "crash", "error", "broken", "because", "impact", "should"])), "The issue contains a concrete problem or goal."); } };
const issue002: Rule = { metadata: meta("CR-ISSUE-002", "issue", "Issue includes reproduction evidence", "A contributor can reproduce or inspect the reported behavior.", "Add steps to reproduce, commands, logs, a minimal example, or a fixture."), evaluate: (context) => issueFinding(issue002, context, issueContains(issueText(context), ["reproduce", "reproducible", "steps to reproduce", "to reproduce", "command", "log", "minimal example", "fixture", "sample"]), "The issue includes reproduction-oriented evidence.") };
const issue003: Rule = { metadata: meta("CR-ISSUE-003", "issue", "Issue states expected behavior", "A contributor can distinguish current behavior from desired behavior.", "Describe actual behavior and the expected or desired result."), evaluate: (context) => issueFinding(issue003, context, issueContains(issueText(context), ["expected", "actual", "desired", "should", "result", "behavior", "behaviour"]), "The issue states expected or observed behavior.") };
const issue004: Rule = { metadata: meta("CR-ISSUE-004", "issue", "Issue defines technical scope", "A contributor can identify the affected area or a plausible starting point.", "Name the affected component, module, file, API, or explicit scope boundary."), evaluate: (context) => issueFinding(issue004, context, issueContains(issueText(context), ["scope", "affected", "component", "module", "file", "api", "area", "located", "starting point", "change"]), "The issue includes a technical scope or starting point.") };
const issue005: Rule = { metadata: meta("CR-ISSUE-005", "issue", "Issue includes acceptance criteria", "A contributor can tell when the requested change is acceptable.", "Add explicit acceptance criteria, checklist items, or Given/When/Then conditions."), evaluate: (context) => issueFinding(issue005, context, issueContains(issueText(context), ["acceptance criteria", "acceptance", "checklist", "criteria", "given", "when", "then", "must satisfy"]), "The issue includes acceptance criteria or equivalent conditions.") };
const issue006: Rule = { metadata: meta("CR-ISSUE-006", "issue", "Issue defines done and validation", "A contributor can identify the testing or documentation evidence required to finish.", "Define done, required tests, verification steps, documentation updates, or other completion evidence."), evaluate: (context) => issueFinding(issue006, context, issueContains(issueText(context), ["definition of done", "done when", "complete when", "tests pass", "testing required", "verification", "verify", "documentation update", "docs update"]), "The issue includes completion or validation guidance.") };

export const coreRules: readonly Rule[] = [setup001, setup002, setup003, setup004, setup005, test001, test002, test003, test004, contrib001, contrib002, contrib003, contrib004, security001, issue001, issue002, issue003, issue004, issue005, issue006];
